### PR TITLE
Fixed bug in multiple occurrences of & in query pairs resulted in a failed parse. Now multiple & are correctly ignored.

### PR DESCRIPTION
**Pull request by TWith2Sugars**
Also included a test.

### CODE REVIEW

**Comment by panesofglass** [comment]
When/why would you have multiple &&?

**Comment by TWith2Sugars** [comment]
No idea, I assume real world urls are just plain bad.

Again the [spec](http://tools.ietf.org/html/rfc3986#section-3.4) doesn't specify a key/value format but since Query pairs is a nice function to do this common format for us it at least makes it more resilient.

**Comment by TWith2Sugars** [comment]
According to [section 2.2](http://tools.ietf.org/html/rfc3986#section-2.2) the & is just reserved as a delimiter so the use of multiple delimiters (even by accident) doesn't seem to fall foul of this.

**Comment by kolektiv** [comment]
Hmmm. That's interesting. As you say, the spec doesn't mention anything about this, it's effectively an informal standard. Where there is a spec, I've erred on the side of strict. I'm in two minds. I can't see any particular harm that it would do (and Postel's principle might well imply that we should be liberal here). On the other hand, it feels like a fairly special case to cope with a measurably broken system. Tempted to say, given that there's 3 of us, that we should vote :)

**Comment by TWith2Sugars** [comment]
+1 for me :)

**Comment by panesofglass** [comment]
What happens if you have an html encoded value in there? Is that allowed? I'll have to check the spec. Example: ?foo=bar&&amp;ref=mem

**Comment by panesofglass** [comment]
Hmm, I'll have to try again on a desktop, as I don't have backticks on my phone.

**Comment by panesofglass** [comment]
I think the above is a bogus example; I just want to make sure it is not dropped in situations where the user would not expect it to be dropped. Does that make sense? I should add a test.

**Comment by TWith2Sugars** [comment]
Ah so "foo" value would be "bar&"

Since "&" is a reserved character then I'm not 100% sure what the best course would be.

**Comment by TWith2Sugars** [comment]
Ah but would "& amp;" be valid? It does say in the spec that & is reserved :)

**Comment by panesofglass** [comment]
You are correct. I was thinking post-url-decoding. With your clarification, I would be -1, as I would prefer strictness over flexibility. I am open to being convinced otherwise. Do you know of other libs that ignore double &?

**Comment by TWith2Sugars** [comment]
I used an [online query parser](http://www.freeformatter.com/url-parser-query-string-splitter.html) to see what it would do based on this url "http://example.com?foo=bar&&amp;ref=mem"

|key|Value
-----|------
|'foo' | bar|
|'amp;ref' | mem|

It seems to strip out multiple & occurrence.

I've also used System.Web.HttpUtility.ParseQueryString with the following code
```
let y = System.Web.HttpUtility.ParseQueryString("foo=bar&&amp;ref=mem")
for k in 0 .. y.Keys.Count-1 do
    printf "key:%A value:%A" y.Keys.[k] (y.GetValues(k))
```

and this is the response

```
key:"foo" value:[|"bar"|]key:<null> value:[|""|]key:"amp;ref" value:[|"mem"|]val it : unit = ()
```

Notice the empty pair?

If we look at other string parses that handle delimiters they produce a similar result.

Take the CSV parser in FSharp.Data

If we run the following code and make the csv parse use & for a separator
```
    let x = FSharp.Data.CsvFile.Parse("foo=bar&&amp;ref=mem",separators="&", hasHeaders=false);;
```

then we get the following:
```
    > x.Rows;;
    val it : seq<FSharp.Data.CsvRow> = seq [[|"foo=bar"; ""; "amp;ref=mem"|]]
```
Notice the empty pair again?

So it seems to me that we have the following choices:
1. Ignore multiple delimiters (effectively this PR) 
2. Include them as an empty pair

If we choose 1 then we are all good, if we choose 2 then we should still accept this PR as it still lets us parse query string without breaking while working on included it as an empty pair.

**Comment by kolektiv** [comment]
I can somewhat see the sanity in making it an empty pair. I have to admit that I do worry about ever adding extra code to be maintained to deal with an edge case. How often do people run in to this problem? I'm also wary of making this change, then another, which would mean a behavioural change for a short period of time. Hmmmm. I have to admit I'm not sure! Is it causing you a big problem?

**Comment by TWith2Sugars** [comment]
Not necessarily extra - more correcting existing code :).

Yeah it has caused a bit of a problem for me, that's what prompted this PR - Real world urls are horrid, this library has helped hugely in navigating them.

**Comment by panesofglass** [comment]
Okay, I'm convinced.

**Comment by kolektiv** [comment]
I think I'm actually reasonably convinced for that case - provided a parser for && as empty KV pair can be written reasonably concisely and effectively, I don't mind that change. It's a loose standard, and I can see that being OK. I'll try and write one at the beginning of next week, provided nobody beats me to it!

I would like to be helpful, and I think this is - if it makes the lib more useful for your real world case @TWith2Sugars - let's do it.

**Comment by TWith2Sugars** [comment]
Right, Sorry for the delay in getting back. I have time to this with the empty pair and will have a go at it today.

**Comment by TWith2Sugars** [comment]
I've also added a check for null/whitespace to so the parser isn't even called in those circumstances.

**Comment by TWith2Sugars** [comment]
Only noticed the build failed. Any ideas why?

**Pull request merged**
