### PR TITLE
Op level 3 matching

### PR DESCRIPTION
**Pull request by mexx**
targets #38

@kolektiv could you review the test cases, I'll look into making them pass.

### CODE REVIEW

**Comment by kolektiv** [comment]
They look pretty good! The code in there is not the most straightforward, but I think it should be fairly clear where the gaps are... Feel free to ping me any queries!

**Comment by mexx** [comment]
I see, that `/test{?list}` and `/test{?keys}` are actually indistinguishable.
I thing we should implement the list variant for the matching.

**Comment by kolektiv** [comment]
Yes, it's one of the areas where URI Templates doesn't quite work as a
bi-directional mapping. I agree that list is probably the right thing to do
given we have no way of knowing whether it's supposed to be keys with no
explode modifier, or a list. List is more general - you could always pair
them in user code.

Agreed :smile:

**Comment by kolektiv** [comment]
(Also, one of the areas where Freya being slightly experimental shows through - I don't think anyone else has really aimed at URI Templates for routing, partly because they're quite complex, but I do think it's very powerful. Plus, when you can then use the *same templates* for both routing to resources, and including in those resources themselves as hypermedia links to other resources... That's potentially very cool for writing genuine hypermedia systems in a layer currently one level up from where Freya sits - for now.)

**Comment by mexx** [comment]
It generally works now.
The current implementation is restrictive about the order of the query parameter. Ideally it wouldn't matter, but for now it's a good compromise :)

**Comment by kolektiv** [comment]
Fantastic! Yes, order of parameters is a bit of an annoying side effect. One day that might have to change for simple practicality, but for now there are worse things :)

I'm going to go ahead and merge, this is a really useful piece of work - thank you! I'll try and push a new pre-release of Freya out tomorrow morning with the latest Arachne pre-release in so that we can see how the Router works with fuller URI Template support.

Thanks again!

**Comment by mexx** [comment]
I'm looking towards it, as I can than use it in my API gateway use case.

**Comment by kolektiv** [comment]
Just merged a release of Freya which includes this - should be a new 3.0 prerelease for Freya out very shortly...

**Comment by mexx** [comment]
I now using it and don't know whether some of the matches are to restrictive.

Should this one work
```
matches "/test{?list*}" "/test" []
```
or this one
```
matches "/test{?list*}" "/test" [ Key "list", List [] ]
```
or neither of them?

**Comment by kolektiv** [comment]
I would *think* the second would be correct - it's an empty collection of
query components. It matched, there were just none. That would be my
interpretation at least. Does that currently match that way?

**Comment by mexx** [comment]
Unfortunate it currently returns the first variant.
I need to have a second look into it. :unamused: 
And it fails on `"/test?key"`, as `=` is currently required.

**Comment by kolektiv** [comment]
Hmm, yeah that's probably worth a look. I will if you don't get to it first!

**Comment by mexx** [comment]
I had a look, second version would be inconsistent to the other operator matching results.
Here the current tests for path segment as example.
```fsharp
matches "/test{/atom}" "/test" []
matches "/test{/list*}" "/test" []
```

**Comment by kolektiv** [comment]
Hmmmm. I wonder about that. Would it be more correct for those to exhibit the same behaviour? Something that matches but with no content - should it show up as empty?

I'll have to look at the RFC again and think - what do you reckon?

**Comment by mexx** [comment]
The problem is that the RFC does not define matching ;)

The RFC example variable values specifies `undef`, in my opinion it's the same as an absent entry in `UriTemplateData`. So I would go with the variant one, which is already used.

I've already extended the test cases and the implementation and send a PR in a minute.

**Pull request merged**
