### PR TITLE
updated dependencies, and removed fsharp.core from packages

### PR DESCRIPTION
**Pull request by kolektiv**

### CODE REVIEW

**Comment by kolektiv** [comment]
Yeah fair enough. It wasn't so much around the packages being official, but more around it not seeming too reliable or predictable. I know what you mean about reproducible though. I'll definitely be keeping an eye on this, because I would also like a world where *everything* is constrained!

**Comment by panesofglass** [comment]
Perhaps @pblasucci can weigh in, as I think it was his request this change satisfied.

**Comment by pblasucci** [comment]
@panesofglass I'm happy to relate my experiences...

@haf I tried combining suave, freya, and fszmq in the same project. This included the appropriate binding redirects of `FSharp.Core.dll` (which I nearly _always_ reference from NuGet in all my projects). Everything compiled fine. But on startup, `freyaRouter` would raise a `TypeInitializationException` indicating problems with types from FSharp.Core. I don't recall exactly the error, but it was something around resolving a tuple. Now, if I omitted using `freyaRouter`, I could still use other parts of Freya and everything worked fine. However, after @kolektiv released the update, I _could_ start using `freyaRouter` again and now everything just works. So, I'm not sure if anything else changed (there are a lot of little moving parts to keep track of afterall). But at a minimum, it seems omitting the dependency on `FSharp.Core.dll` helped.

Personally, I suspect this is actually an issue with FSharp.Core, as the same binding redirects which resolve compile-time issues really ought to hold at run-time. Thus free library and application authors from having to deal with these shenanigans. Additionally, I'm reviewing the other libraries I maintain to see if there are more places where I can drop the explicit dependency. My feeling is, in general, libraries should have as few dependencies as possible.

Anyway, I'm not sure if this helps. But that's the state of things.

**Comment by haf** [comment]
@pblasucci Thanks for telling us about it. My reasoning goes F# Core is a dependency, so it should be explicit to make things easier; at some point in the future libs will start referencing F# 4.0 or F# 5.0 and then some will work well with others but crash in some combinations, all without being able to debug it.

If you still have the broken runtime commit of your code; perhaps we could present it to the F# team for review so they can take action accordingly?

**Comment by panesofglass** [comment]
@haf makes a good point. Also, once we start doing things for .NET Core, we will have to make NuGet package references, so we will need to make these explicit dependencies.

**Pull request merged**
