### PR TITLE
Exploratory - Do Not Merge!

### PR DESCRIPTION
**Pull request by kolektiv**
Exploring whether the build for this still seemingly works, at a base level. Profile targets won't do anything, but does it still build and run a bit?

### CODE REVIEW

**Comment by panesofglass** [comment]
XBuild has some problems:
- ToolsVersion 14 doesn't exist in mono
- ToolsVersion 4.0 doesn't support .NET 4.5.2

Looks like AppVeyor is also unhappy.

**Comment by kolektiv** [comment]
Yes, that was the kind of exploration that interested me :) I'm not sure how you're even supposed to do xplat portable at the moment. I don't know whether it's even a thing, and trying to work out the story and portable in general is like punching smoke. Still, interesting to see how it gets more or less fixed over time...

**Comment by kolektiv** [comment]
Right, so AppVeyor is now happy (and after a switch to xunit, which I'm having better results with these days, and is now used in Aether, Chiron, etc. with much better support for FsCheck, etc.)

I've got no clue what you're supposed to do about travis though at the moment, may just park that aspect until I've got proper time to look at it! For 3.0 maybe...

**Comment by kolektiv** [comment]
So, the latest version is now portable (profile259) as well as net40. The packages produced now contain two sets of assemblies, etc. I've also updated the naming in here to be more F# like, in that static members on types (which are effectively similar to module level functions) are named like module level functions (camelCase rather than PascalCase), to feel more native. This applies to the common format, parse and tryParse functions, as well as any type level optics.

I'm not sure what to do about travis, as i'd like to get this merged in, and a first pre-release out to start playing with Freya 3.0-bXXX. I don't know how long it's going to be before some kind of xbuild can support the kinds of solution/projects required to do xplat portable libs.

Temporarily, I'm going to ignore/disable the travis builds and merge this anyway. It's not great and i'm not pleased, but i'm not sure what more can be done today.

**Comment by panesofglass** [comment]
@kolektiv probably best to not build the PCL on Travis.

**Comment by panesofglass** [comment]
I'll send a PR to disable PCL builds if I can sort it out.

**Pull request merged**
